/**
 * Enterprise Menu Configuration
 *
 * Centralized menu configuration for the application.
 * This file defines the structure, hierarchy, and metadata for all menu items.
 */

import {
    IconLayoutDashboard,
    IconShoppingCart,
    IconPackage,
    IconUsers,
    IconCategory,
    IconScissors,
    IconUserCheck,
    IconCalendarEvent,
    IconClock,
    IconChartBar,
    IconFileAnalytics,
    IconChartPie,
    IconCoin,
    IconShieldLock,
    IconUserShield,
    IconUserCog,
    IconTable,
    IconUserPlus,
    IconCreditCard,
    IconBell,
    IconDatabase,
    IconHeartbeat,
    IconLink,
    IconBriefcase,
    IconChartLine,
    IconReportAnalytics,
    IconFileSpreadsheet,
    IconFileText,
    IconCalendarStats,
    IconDownload,
    IconStar,
    IconBox,
    IconReceipt,
    IconTax,
    IconTrendingUp,
    IconSettings,
    IconHome,
    IconTruck,
    IconClipboardList,
    IconBuildingStore,
    IconBuildingWarehouse,
    IconBarcode,
    IconAlertTriangle,
    IconRefresh,
    IconWallet,
    IconPigMoney,
    IconBuildingBank,
    IconCalculator,
    IconFileInvoice,
    IconFileReport,
    IconMoneybag,
    IconUserDollar,
    IconId,
    IconSchool,
    IconCalendar,
    IconDeviceAnalytics,
    IconBrandGoogle,
    IconMail,
    IconBrandWhatsapp,
    IconPhone,
    IconDiscount,
    IconGift,
    IconSpeakerphone,
    IconBrandFacebook,
    IconAffiliate,
    IconTags,
    IconBulb,
    IconRocket,
    IconChartDots,
    IconActivity,
    IconCloud,
    IconKey,
    IconLanguage,
    IconPalette,
    IconPlugConnected,
    IconWorldWww,
    IconCode,
} from "@tabler/icons-react";

/**
 * Menu Item Types
 */
export const MENU_TYPES = {
    SINGLE: 'single',
    DROPDOWN: 'dropdown',
    MEGA: 'mega',
    DIVIDER: 'divider',
};

/**
 * Badge Variants
 */
export const BADGE_VARIANTS = {
    NEW: { text: 'New', color: 'bg-green-500' },
    BETA: { text: 'Beta', color: 'bg-blue-500' },
    PRO: { text: 'Pro', color: 'bg-purple-500' },
    ENTERPRISE: { text: 'Enterprise', color: 'bg-purple-600' },
    COMING_SOON: { text: 'Soon', color: 'bg-gray-500' },
    HOT: { text: 'Hot', color: 'bg-red-500' },
    UPDATE: { text: 'Updated', color: 'bg-orange-500' },
};

/**
 * Menu Categories
 */
export const MENU_CATEGORIES = {
    OVERVIEW: 'OVERVIEW',
    OPERATIONS: 'OPERATIONS',
    INVENTORY: 'INVENTORY MANAGEMENT',
    CUSTOMERS: 'CUSTOMER RELATIONSHIP',
    SERVICES: 'SERVICE MANAGEMENT',
    ANALYTICS: 'ANALYTICS & INSIGHTS',
    REPORTING: 'ENTERPRISE REPORTING',
    FINANCE: 'FINANCE & ACCOUNTING',
    PROCUREMENT: 'PROCUREMENT & SUPPLY CHAIN',
    HR: 'HUMAN RESOURCES',
    MARKETING: 'MARKETING & CRM',
    INTEGRATIONS: 'INTEGRATIONS',
    ADMINISTRATION: 'ADMINISTRATION',
    SETTINGS: 'SYSTEM CONFIGURATION',
};

/**
 * Main Menu Configuration
 */
export const MENU_STRUCTURE = [
    // ==================== OVERVIEW ====================
    {
        category: MENU_CATEGORIES.OVERVIEW,
        priority: 1,
        icon: IconHome,
        items: [
            {
                id: 'dashboard',
                type: MENU_TYPES.SINGLE,
                title: 'Dashboard',
                route: 'dashboard',
                icon: IconLayoutDashboard,
                permissions: ['dashboard-access'],
                badge: null,
                description: 'Main dashboard overview',
            },
            {
                id: 'business-intelligence',
                type: MENU_TYPES.SINGLE,
                title: 'Business Intelligence',
                route: 'business-intelligence',
                icon: IconChartLine,
                permissions: ['dashboard-access'],
                badge: BADGE_VARIANTS.NEW,
                description: 'Advanced analytics and insights',
            },
        ],
    },

    // ==================== OPERATIONS ====================
    {
        category: MENU_CATEGORIES.OPERATIONS,
        priority: 2,
        icon: IconShoppingCart,
        items: [
            {
                id: 'pos',
                type: MENU_TYPES.SINGLE,
                title: 'Point of Sale',
                route: 'transactions.index',
                icon: IconShoppingCart,
                permissions: ['transactions-access'],
                badge: null,
                description: 'Process sales transactions',
                shortcut: 'Ctrl+P',
            },
            {
                id: 'transaction-history',
                type: MENU_TYPES.SINGLE,
                title: 'Transaction History',
                route: 'transactions.history',
                icon: IconClock,
                permissions: ['transactions-access'],
                badge: null,
                description: 'View past transactions',
            },
        ],
    },

    // ==================== INVENTORY ====================
    {
        category: MENU_CATEGORIES.INVENTORY,
        priority: 3,
        icon: IconPackage,
        items: [
            {
                id: 'categories',
                type: MENU_TYPES.SINGLE,
                title: 'Product Categories',
                route: 'categories.index',
                icon: IconCategory,
                permissions: ['categories-access'],
                badge: null,
                description: 'Manage product categories',
            },
            {
                id: 'products',
                type: MENU_TYPES.SINGLE,
                title: 'Products',
                route: 'products.index',
                icon: IconPackage,
                permissions: ['products-access'],
                badge: null,
                description: 'Manage products and inventory',
            },
        ],
    },

    // ==================== CUSTOMERS ====================
    {
        category: MENU_CATEGORIES.CUSTOMERS,
        priority: 4,
        icon: IconUsers,
        items: [
            {
                id: 'customers',
                type: MENU_TYPES.SINGLE,
                title: 'Customer Database',
                route: 'customers.index',
                icon: IconUsers,
                permissions: ['customers-access'],
                badge: null,
                description: 'Manage customer information',
            },
        ],
    },

    // ==================== SERVICE MANAGEMENT ====================
    {
        category: MENU_CATEGORIES.SERVICES,
        priority: 5,
        icon: IconScissors,
        items: [
            {
                id: 'services',
                type: MENU_TYPES.SINGLE,
                title: 'Services',
                route: 'services.index',
                icon: IconScissors,
                permissions: ['services-access'],
                badge: null,
                description: 'Manage available services',
            },
            {
                id: 'staff',
                type: MENU_TYPES.SINGLE,
                title: 'Staff Management',
                route: 'staff.index',
                icon: IconUserCheck,
                permissions: ['staff-access'],
                badge: null,
                description: 'Manage staff members',
            },
            {
                id: 'appointments',
                type: MENU_TYPES.SINGLE,
                title: 'Appointments',
                route: 'appointments.index',
                icon: IconCalendarEvent,
                permissions: ['appointments-access'],
                badge: null,
                description: 'Manage bookings and appointments',
            },
        ],
    },

    // ==================== ANALYTICS ====================
    {
        category: MENU_CATEGORIES.ANALYTICS,
        priority: 6,
        icon: IconChartBar,
        items: [
            {
                id: 'reports-overview',
                type: MENU_TYPES.SINGLE,
                title: 'Reports Overview',
                route: 'reports.index',
                icon: IconFileAnalytics,
                permissions: ['reports-access'],
                badge: null,
                description: 'Quick access to standard reports',
            },
            {
                id: 'sales-report',
                type: MENU_TYPES.SINGLE,
                title: 'Sales Report',
                route: 'reports.sales-report',
                icon: IconChartBar,
                permissions: ['reports-access'],
                badge: null,
                description: 'Sales performance analysis',
            },
            {
                id: 'products-report',
                type: MENU_TYPES.SINGLE,
                title: 'Products Report',
                route: 'reports.products',
                icon: IconChartPie,
                permissions: ['reports-access'],
                badge: null,
                description: 'Product performance metrics',
            },
            {
                id: 'customers-report',
                type: MENU_TYPES.SINGLE,
                title: 'Customers Report',
                route: 'reports.customers',
                icon: IconUsers,
                permissions: ['reports-access'],
                badge: null,
                description: 'Customer analytics',
            },
            {
                id: 'profit-report',
                type: MENU_TYPES.SINGLE,
                title: 'Profit Report',
                route: 'reports.profit',
                icon: IconCoin,
                permissions: ['reports-access'],
                badge: null,
                description: 'Profit and margin analysis',
            },
        ],
    },

    // ==================== ENTERPRISE REPORTING ====================
    {
        category: MENU_CATEGORIES.REPORTING,
        priority: 7,
        icon: IconReportAnalytics,
        items: [
            {
                id: 'report-center',
                type: MENU_TYPES.DROPDOWN,
                title: 'Report Center',
                icon: IconReportAnalytics,
                permissions: ['enterprise-reports-access', 'reports-view'],
                badge: BADGE_VARIANTS.ENTERPRISE,
                description: 'Advanced reporting hub',
                children: [
                    {
                        id: 'enterprise-reports-dashboard',
                        title: 'Enterprise Dashboard',
                        route: 'enterprise.reports.index',
                        icon: IconLayoutDashboard,
                        permissions: ['enterprise-reports-access'],
                        description: 'Advanced analytics dashboard',
                    },
                    {
                        id: 'saved-reports',
                        title: 'Saved Reports',
                        route: 'enterprise.reports.saved',
                        icon: IconStar,
                        permissions: ['reports-save'],
                        description: 'Your saved report templates',
                    },
                    {
                        id: 'scheduled-reports',
                        title: 'Scheduled Reports',
                        route: 'enterprise.reports.schedules',
                        icon: IconCalendarStats,
                        permissions: ['reports-schedule'],
                        description: 'Automated report scheduling',
                    },
                ],
            },
            {
                id: 'report-types',
                type: MENU_TYPES.DROPDOWN,
                title: 'Report Types',
                icon: IconFileSpreadsheet,
                permissions: ['reports-view'],
                badge: null,
                description: 'All available report types',
                children: [
                    {
                        id: 'enterprise-sales',
                        title: 'Sales Report',
                        route: 'enterprise.reports.sales',
                        icon: IconReceipt,
                        permissions: ['reports-sales'],
                    },
                    {
                        id: 'enterprise-products',
                        title: 'Products Report',
                        route: 'enterprise.reports.products',
                        icon: IconBox,
                        permissions: ['reports-products'],
                    },
                    {
                        id: 'enterprise-customers',
                        title: 'Customers Report',
                        route: 'enterprise.reports.customers',
                        icon: IconUsers,
                        permissions: ['reports-customers'],
                    },
                    {
                        id: 'enterprise-profit',
                        title: 'Profit Report',
                        route: 'enterprise.reports.profit',
                        icon: IconTrendingUp,
                        permissions: ['reports-profit'],
                    },
                    {
                        id: 'tax-report',
                        title: 'Tax Report',
                        route: 'enterprise.reports.tax',
                        icon: IconTax,
                        permissions: ['reports-tax'],
                    },
                    {
                        id: 'inventory-report',
                        title: 'Inventory Report',
                        route: 'enterprise.reports.inventory',
                        icon: IconPackage,
                        permissions: ['reports-inventory'],
                    },
                ],
            },
        ],
    },

    // ==================== FINANCE & ACCOUNTING ====================
    {
        category: MENU_CATEGORIES.FINANCE,
        priority: 8,
        icon: IconWallet,
        items: [
            {
                id: 'finance-dashboard',
                type: MENU_TYPES.SINGLE,
                title: 'Finance Dashboard',
                route: 'finance.dashboard',
                icon: IconChartLine,
                permissions: ['finance-access'],
                badge: BADGE_VARIANTS.PRO,
                description: 'Financial overview and metrics',
            },
            {
                id: 'accounting',
                type: MENU_TYPES.DROPDOWN,
                title: 'Accounting',
                icon: IconCalculator,
                permissions: ['accounting-access'],
                badge: null,
                description: 'Accounting operations',
                children: [
                    {
                        id: 'general-ledger',
                        title: 'General Ledger',
                        route: 'finance.general-ledger',
                        icon: IconTable,
                        permissions: ['ledger-access'],
                    },
                    {
                        id: 'journal-entries',
                        title: 'Journal Entries',
                        route: 'finance.journal-entries',
                        icon: IconFileText,
                        permissions: ['journal-access'],
                    },
                    {
                        id: 'chart-of-accounts',
                        title: 'Chart of Accounts',
                        route: 'finance.chart-of-accounts',
                        icon: IconClipboardList,
                        permissions: ['accounts-access'],
                    },
                ],
            },
            {
                id: 'invoicing',
                type: MENU_TYPES.DROPDOWN,
                title: 'Invoicing',
                icon: IconFileInvoice,
                permissions: ['invoices-access'],
                badge: null,
                description: 'Invoice management',
                children: [
                    {
                        id: 'invoices-list',
                        title: 'All Invoices',
                        route: 'finance.invoices.index',
                        icon: IconTable,
                        permissions: ['invoices-view'],
                    },
                    {
                        id: 'create-invoice',
                        title: 'Create Invoice',
                        route: 'finance.invoices.create',
                        icon: IconFileInvoice,
                        permissions: ['invoices-create'],
                    },
                    {
                        id: 'recurring-invoices',
                        title: 'Recurring Invoices',
                        route: 'finance.invoices.recurring',
                        icon: IconRefresh,
                        permissions: ['invoices-recurring'],
                    },
                ],
            },
            {
                id: 'payments',
                type: MENU_TYPES.DROPDOWN,
                title: 'Payments',
                icon: IconCreditCard,
                permissions: ['payments-access'],
                badge: null,
                description: 'Payment processing',
                children: [
                    {
                        id: 'payment-records',
                        title: 'Payment Records',
                        route: 'finance.payments.index',
                        icon: IconReceipt,
                        permissions: ['payments-view'],
                    },
                    {
                        id: 'payment-methods',
                        title: 'Payment Methods',
                        route: 'finance.payment-methods',
                        icon: IconCreditCard,
                        permissions: ['payment-methods-manage'],
                    },
                ],
            },
            {
                id: 'banking',
                type: MENU_TYPES.DROPDOWN,
                title: 'Banking',
                icon: IconBuildingBank,
                permissions: ['banking-access'],
                badge: null,
                description: 'Bank account management',
                children: [
                    {
                        id: 'bank-accounts',
                        title: 'Bank Accounts',
                        route: 'finance.bank-accounts',
                        icon: IconBuildingBank,
                        permissions: ['bank-accounts-access'],
                    },
                    {
                        id: 'bank-reconciliation',
                        title: 'Reconciliation',
                        route: 'finance.reconciliation',
                        icon: IconClipboardList,
                        permissions: ['bank-reconciliation-access'],
                    },
                ],
            },
            {
                id: 'expenses',
                type: MENU_TYPES.SINGLE,
                title: 'Expense Management',
                route: 'finance.expenses',
                icon: IconMoneybag,
                permissions: ['expenses-access'],
                badge: null,
                description: 'Track and manage expenses',
            },
            {
                id: 'budgets',
                type: MENU_TYPES.SINGLE,
                title: 'Budget Planning',
                route: 'finance.budgets',
                icon: IconPigMoney,
                permissions: ['budgets-access'],
                badge: null,
                description: 'Budget allocation and tracking',
            },
        ],
    },

    // ==================== PROCUREMENT & SUPPLY CHAIN ====================
    {
        category: MENU_CATEGORIES.PROCUREMENT,
        priority: 9,
        icon: IconTruck,
        items: [
            {
                id: 'purchase-orders',
                type: MENU_TYPES.DROPDOWN,
                title: 'Purchase Orders',
                icon: IconClipboardList,
                permissions: ['purchase-orders-access'],
                badge: null,
                description: 'Manage purchase orders',
                children: [
                    {
                        id: 'po-list',
                        title: 'All Purchase Orders',
                        route: 'procurement.purchase-orders.index',
                        icon: IconTable,
                        permissions: ['purchase-orders-view'],
                    },
                    {
                        id: 'create-po',
                        title: 'Create Purchase Order',
                        route: 'procurement.purchase-orders.create',
                        icon: IconClipboardList,
                        permissions: ['purchase-orders-create'],
                    },
                ],
            },
            {
                id: 'suppliers',
                type: MENU_TYPES.DROPDOWN,
                title: 'Suppliers',
                icon: IconBuildingStore,
                permissions: ['suppliers-access'],
                badge: null,
                description: 'Supplier management',
                children: [
                    {
                        id: 'suppliers-list',
                        title: 'All Suppliers',
                        route: 'procurement.suppliers',
                        icon: IconTable,
                        permissions: ['suppliers-view'],
                    },
                    {
                        id: 'supplier-performance',
                        title: 'Supplier Performance',
                        route: 'procurement.suppliers.analytics',
                        icon: IconChartBar,
                        permissions: ['suppliers-analytics'],
                    },
                ],
            },
            {
                id: 'warehouses',
                type: MENU_TYPES.DROPDOWN,
                title: 'Warehouses',
                icon: IconBuildingWarehouse,
                permissions: ['warehouses-access'],
                badge: BADGE_VARIANTS.PRO,
                description: 'Multi-warehouse management',
                children: [
                    {
                        id: 'warehouses-list',
                        title: 'All Warehouses',
                        route: 'procurement.warehouses',
                        icon: IconBuildingWarehouse,
                        permissions: ['warehouses-view'],
                    },
                    {
                        id: 'stock-transfers',
                        title: 'Stock Transfers',
                        route: 'procurement.stock-transfers',
                        icon: IconTruck,
                        permissions: ['stock-transfers-access'],
                    },
                    {
                        id: 'stock-adjustments',
                        title: 'Stock Adjustments',
                        route: 'procurement.stock-adjustments',
                        icon: IconRefresh,
                        permissions: ['stock-adjustments-access'],
                    },
                ],
            },
            // Inventory Tracking - Coming Soon
            // {
            //     id: 'inventory-tracking',
            //     type: MENU_TYPES.DROPDOWN,
            //     title: 'Inventory Tracking',
            //     icon: IconBarcode,
            //     permissions: ['inventory-tracking-access'],
            //     badge: null,
            //     description: 'Advanced inventory tracking',
            //     children: [
            //         {
            //             id: 'batch-tracking',
            //             title: 'Batch/Lot Tracking',
            //             route: 'procurement.batch-tracking',
            //             icon: IconBarcode,
            //             permissions: ['batch-tracking-access'],
            //         },
            //         {
            //             id: 'serial-numbers',
            //             title: 'Serial Numbers',
            //             route: 'procurement.serial-numbers',
            //             icon: IconBarcode,
            //             permissions: ['serial-tracking-access'],
            //         },
            //         {
            //             id: 'expiry-tracking',
            //             title: 'Expiry Management',
            //             route: 'procurement.expiry-tracking',
            //             icon: IconAlertTriangle,
            //             permissions: ['expiry-tracking-access'],
            //         },
            //     ],
            // },
            {
                id: 'receiving',
                type: MENU_TYPES.SINGLE,
                title: 'Receiving',
                route: 'procurement.receiving',
                icon: IconPackage,
                permissions: ['receiving-access'],
                badge: null,
                description: 'Receive and inspect goods',
            },
        ],
    },

    // ==================== HUMAN RESOURCES ====================
    {
        category: MENU_CATEGORIES.HR,
        priority: 10,
        icon: IconId,
        items: [
            {
                id: 'hr-dashboard',
                type: MENU_TYPES.SINGLE,
                title: 'HR Dashboard',
                route: 'hr.dashboard',
                icon: IconLayoutDashboard,
                permissions: ['hr-access'],
                badge: BADGE_VARIANTS.PRO,
                description: 'Human resources overview',
            },
            {
                id: 'employees',
                type: MENU_TYPES.DROPDOWN,
                title: 'Employee Management',
                icon: IconUsers,
                permissions: ['employees-access'],
                badge: null,
                description: 'Manage employees',
                children: [
                    {
                        id: 'employees-list',
                        title: 'All Employees',
                        route: 'hr.employees',
                        icon: IconTable,
                        permissions: ['employees-view'],
                    },
                    {
                        id: 'employee-profiles',
                        title: 'Employee Profiles',
                        route: 'hr.employees',
                        icon: IconId,
                        permissions: ['employee-profiles-view'],
                    },
                    {
                        id: 'departments',
                        title: 'Departments',
                        route: 'hr.departments',
                        icon: IconBuildingStore,
                        permissions: ['departments-access'],
                    },
                ],
            },
            {
                id: 'attendance',
                type: MENU_TYPES.DROPDOWN,
                title: 'Attendance',
                icon: IconCalendar,
                permissions: ['attendance-access'],
                badge: null,
                description: 'Attendance tracking',
                children: [
                    {
                        id: 'attendance-tracker',
                        title: 'Attendance Tracker',
                        route: 'hr.attendance',
                        icon: IconClock,
                        permissions: ['attendance-view'],
                    },
                    {
                        id: 'leave-management',
                        title: 'Leave Management',
                        route: 'hr.leave-management',
                        icon: IconCalendarEvent,
                        permissions: ['leave-management-access'],
                    },
                    {
                        id: 'shifts',
                        title: 'Shift Management',
                        route: 'hr.shifts',
                        icon: IconClock,
                        permissions: ['shifts-access'],
                    },
                ],
            },
            {
                id: 'payroll',
                type: MENU_TYPES.DROPDOWN,
                title: 'Payroll',
                icon: IconUserDollar,
                permissions: ['payroll-access'],
                badge: BADGE_VARIANTS.PRO,
                description: 'Payroll processing',
                children: [
                    {
                        id: 'payroll-processing',
                        title: 'Process Payroll',
                        route: 'hr.payroll.process',
                        icon: IconCalculator,
                        permissions: ['payroll-process'],
                    },
                    {
                        id: 'payroll-history',
                        title: 'Payroll History',
                        route: 'hr.payroll',
                        icon: IconTable,
                        permissions: ['payroll-view'],
                    },
                    {
                        id: 'salary-structure',
                        title: 'Salary Structure',
                        route: 'hr.salary-structure',
                        icon: IconCoin,
                        permissions: ['salary-structure-access'],
                    },
                ],
            },
            {
                id: 'recruitment',
                type: MENU_TYPES.DROPDOWN,
                title: 'Recruitment',
                icon: IconUserPlus,
                permissions: ['recruitment-access'],
                badge: null,
                description: 'Recruitment management',
                children: [
                    {
                        id: 'job-postings',
                        title: 'Job Postings',
                        route: 'hr.recruitment',
                        icon: IconSpeakerphone,
                        permissions: ['job-postings-access'],
                    },
                    {
                        id: 'candidates',
                        title: 'Candidates',
                        route: 'hr.recruitment',
                        icon: IconUsers,
                        permissions: ['candidates-access'],
                    },
                ],
            },
            {
                id: 'training',
                type: MENU_TYPES.SINGLE,
                title: 'Training & Development',
                route: 'hr.training',
                icon: IconSchool,
                permissions: ['training-access'],
                badge: null,
                description: 'Employee training programs',
            },
            {
                id: 'performance',
                type: MENU_TYPES.SINGLE,
                title: 'Performance Reviews',
                route: 'hr.performance',
                icon: IconChartBar,
                permissions: ['performance-access'],
                badge: null,
                description: 'Employee performance management',
            },
        ],
    },

    // ==================== MARKETING & CRM ====================
    {
        category: MENU_CATEGORIES.MARKETING,
        priority: 11,
        icon: IconSpeakerphone,
        items: [
            {
                id: 'marketing-dashboard',
                type: MENU_TYPES.SINGLE,
                title: 'Marketing Dashboard',
                route: 'marketing.dashboard',
                icon: IconChartLine,
                permissions: ['marketing-access'],
                badge: BADGE_VARIANTS.PRO,
                description: 'Marketing metrics and campaigns',
            },
            {
                id: 'campaigns',
                type: MENU_TYPES.DROPDOWN,
                title: 'Campaigns',
                icon: IconRocket,
                permissions: ['campaigns-access'],
                badge: null,
                description: 'Marketing campaigns',
                children: [
                    {
                        id: 'email-campaigns',
                        title: 'Email Campaigns',
                        route: 'marketing.campaigns.email',
                        icon: IconMail,
                        permissions: ['email-campaigns-access'],
                    },
                    {
                        id: 'sms-campaigns',
                        title: 'SMS Campaigns',
                        route: 'marketing.campaigns.sms',
                        icon: IconPhone,
                        permissions: ['sms-campaigns-access'],
                    },
                    {
                        id: 'whatsapp-campaigns',
                        title: 'WhatsApp Campaigns',
                        route: 'marketing.campaigns.whatsapp',
                        icon: IconBrandWhatsapp,
                        permissions: ['whatsapp-campaigns-access'],
                    },
                ],
            },
            {
                id: 'promotions',
                type: MENU_TYPES.DROPDOWN,
                title: 'Promotions',
                icon: IconDiscount,
                permissions: ['promotions-access'],
                badge: null,
                description: 'Promotional offers',
                children: [
                    {
                        id: 'discounts',
                        title: 'Discounts',
                        route: 'marketing.discounts',
                        icon: IconDiscount,
                        permissions: ['discounts-access'],
                    },
                    {
                        id: 'coupons',
                        title: 'Coupons',
                        route: 'marketing.coupons',
                        icon: IconTags,
                        permissions: ['coupons-access'],
                    },
                    {
                        id: 'vouchers',
                        title: 'Gift Vouchers',
                        route: 'marketing.vouchers',
                        icon: IconGift,
                        permissions: ['vouchers-access'],
                    },
                ],
            },
            {
                id: 'loyalty-program',
                type: MENU_TYPES.DROPDOWN,
                title: 'Loyalty Program',
                icon: IconStar,
                permissions: ['loyalty-access'],
                badge: BADGE_VARIANTS.NEW,
                description: 'Customer loyalty management',
                children: [
                    {
                        id: 'loyalty-settings',
                        title: 'Program Settings',
                        route: 'marketing.loyalty-settings',
                        icon: IconSettings,
                        permissions: ['loyalty-settings-access'],
                    },
                    {
                        id: 'loyalty-tiers',
                        title: 'Membership Tiers',
                        route: 'marketing.loyalty-tiers',
                        icon: IconStar,
                        permissions: ['loyalty-tiers-access'],
                    },
                    {
                        id: 'rewards',
                        title: 'Rewards',
                        route: 'marketing.rewards',
                        icon: IconGift,
                        permissions: ['rewards-access'],
                    },
                ],
            },
            {
                id: 'social-media',
                type: MENU_TYPES.DROPDOWN,
                title: 'Social Media',
                icon: IconBrandFacebook,
                permissions: ['social-media-access'],
                badge: null,
                description: 'Social media management',
                children: [
                    {
                        id: 'social-posts',
                        title: 'Post Management',
                        route: 'marketing.social-media',
                        icon: IconBrandFacebook,
                        permissions: ['social-posts-access'],
                    },
                    {
                        id: 'social-analytics',
                        title: 'Social Analytics',
                        route: 'marketing.social-media',
                        icon: IconChartBar,
                        permissions: ['social-analytics-access'],
                    },
                ],
            },
            {
                id: 'referrals',
                type: MENU_TYPES.SINGLE,
                title: 'Referral Program',
                route: 'marketing.referrals',
                icon: IconAffiliate,
                permissions: ['referrals-access'],
                badge: null,
                description: 'Customer referral tracking',
            },
            {
                id: 'market-analysis',
                type: MENU_TYPES.SINGLE,
                title: 'Market Analysis',
                route: 'marketing.market-analysis',
                icon: IconChartDots,
                permissions: ['market-analysis-access'],
                badge: null,
                description: 'Market trends and insights',
            },
        ],
    },

    // ==================== INTEGRATIONS ====================
    {
        category: MENU_CATEGORIES.INTEGRATIONS,
        priority: 12,
        icon: IconPlugConnected,
        items: [
            {
                id: 'integration-hub',
                type: MENU_TYPES.SINGLE,
                title: 'Integration Hub',
                route: 'integrations.dashboard',
                icon: IconPlugConnected,
                permissions: ['integrations-access'],
                badge: BADGE_VARIANTS.NEW,
                description: 'Manage all integrations',
            },
            {
                id: 'api-management',
                type: MENU_TYPES.DROPDOWN,
                title: 'API Management',
                icon: IconCode,
                permissions: ['api-access'],
                badge: null,
                description: 'API keys and webhooks',
                children: [
                    {
                        id: 'api-keys',
                        title: 'API Keys',
                        route: 'integrations.api-keys',
                        icon: IconKey,
                        permissions: ['api-keys-access'],
                    },
                    {
                        id: 'webhooks',
                        title: 'Webhooks',
                        route: 'integrations.webhooks',
                        icon: IconWorldWww,
                        permissions: ['webhooks-access'],
                    },
                    {
                        id: 'api-logs',
                        title: 'API Logs',
                        route: 'integrations.api-logs',
                        icon: IconFileText,
                        permissions: ['api-logs-access'],
                    },
                ],
            },
            {
                id: 'third-party',
                type: MENU_TYPES.DROPDOWN,
                title: 'Third-Party Apps',
                icon: IconCloud,
                permissions: ['third-party-access'],
                badge: null,
                description: 'External integrations',
                children: [
                    {
                        id: 'google-integration',
                        title: 'Google Services',
                        route: 'integrations.google-suite',
                        icon: IconBrandGoogle,
                        permissions: ['google-integration-access'],
                    },
                    {
                        id: 'email-integration',
                        title: 'Email Services',
                        route: 'integrations.email-platform',
                        icon: IconMail,
                        permissions: ['email-integration-access'],
                    },
                    {
                        id: 'whatsapp-integration',
                        title: 'WhatsApp Business',
                        route: 'integrations.whatsapp-business',
                        icon: IconBrandWhatsapp,
                        permissions: ['whatsapp-integration-access'],
                    },
                ],
            },
        ],
    },

    // ==================== ADMINISTRATION ====================
    {
        category: MENU_CATEGORIES.ADMINISTRATION,
        priority: 13,
        icon: IconUserCog,
        items: [
            {
                id: 'users-management',
                type: MENU_TYPES.DROPDOWN,
                title: 'User Management',
                icon: IconUserCog,
                permissions: ['users-access'],
                badge: null,
                description: 'Manage system users',
                children: [
                    {
                        id: 'users-list',
                        title: 'All Users',
                        route: 'users.index',
                        icon: IconTable,
                        permissions: ['users-access'],
                    },
                    {
                        id: 'users-create',
                        title: 'Add User',
                        route: 'users.create',
                        icon: IconUserPlus,
                        permissions: ['users-create'],
                    },
                ],
            },
            {
                id: 'roles-permissions',
                type: MENU_TYPES.DROPDOWN,
                title: 'Roles & Permissions',
                icon: IconShieldLock,
                permissions: ['roles-access', 'permissions-access'],
                badge: null,
                description: 'Configure access control',
                children: [
                    {
                        id: 'roles',
                        title: 'Role Management',
                        route: 'roles.index',
                        icon: IconUserShield,
                        permissions: ['roles-access'],
                    },
                    {
                        id: 'permissions',
                        title: 'Permission Management',
                        route: 'permissions.index',
                        icon: IconShieldLock,
                        permissions: ['permissions-access'],
                    },
                ],
            },
        ],
    },

    // ==================== SYSTEM CONFIGURATION ====================
    {
        category: MENU_CATEGORIES.SETTINGS,
        priority: 14,
        icon: IconSettings,
        items: [
            {
                id: 'payment-gateway',
                type: MENU_TYPES.SINGLE,
                title: 'Payment Gateway',
                route: 'settings.payments.edit',
                icon: IconCreditCard,
                permissions: ['payment-settings-access'],
                badge: null,
                description: 'Configure payment providers',
            },
            {
                id: 'payment-merchants',
                type: MENU_TYPES.SINGLE,
                title: 'Payment Merchants',
                route: 'merchants.index',
                icon: IconWallet,
                permissions: [],
                badge: { text: 'Multi-Tenant', color: 'bg-blue-500' },
                description: 'Manage merchant credentials',
            },
            {
                id: 'store-merchants',
                type: MENU_TYPES.SINGLE,
                title: 'Store-Merchant Mapping',
                route: 'store-merchants.index',
                icon: IconLink,
                permissions: [],
                badge: null,
                description: 'Map stores to merchants',
            },
            {
                id: 'notifications',
                type: MENU_TYPES.SINGLE,
                title: 'Notifications',
                route: 'settings.notifications.edit',
                icon: IconBell,
                permissions: ['notification-settings-access'],
                badge: null,
                description: 'Notification preferences',
            },
            {
                id: 'backup',
                type: MENU_TYPES.SINGLE,
                title: 'Backup & Restore',
                route: 'settings.backup.index',
                icon: IconDatabase,
                permissions: ['backup-access'],
                badge: null,
                description: 'Database backup management',
            },
            {
                id: 'system-health',
                type: MENU_TYPES.SINGLE,
                title: 'System Health',
                route: 'system-health',
                icon: IconHeartbeat,
                permissions: ['dashboard-access'],
                badge: { text: 'Monitor', color: 'bg-red-500' },
                description: 'System performance monitoring',
            },
        ],
    },
];

/**
 * Quick Access Menu (for frequently used items)
 */
export const QUICK_ACCESS_MENU = [
    'pos',
    'dashboard',
    'products',
    'customers',
];

/**
 * Admin Quick Links
 */
export const ADMIN_QUICK_LINKS = [
    'users-management',
    'roles-permissions',
    'system-health',
];

export default MENU_STRUCTURE;
